
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class modifyemployee extends javax.swing.JFrame {
   Connection conn = null;
    final void getconnection()
    {
   
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
            } catch (InstantiationException | IllegalAccessException ex) {
                Logger.getLogger(newemployee.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/employee","root","");
            } catch (SQLException ex) {
                Logger.getLogger(newemployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(newemployee.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    

    /**
     * Creates new form modifyemployee
     */
    public modifyemployee() {
        initComponents();
         getconnection();
        ta1.setVisible(false);
        ta2.setVisible(false);
        ta3.setVisible(false);
        ta4.setVisible(false);
        ta5.setVisible(false);
        ta6.setVisible(false);
        ta7.setVisible(false);
        ta8.setVisible(false);
        ta9.setVisible(false);
       
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tem = new javax.swing.JTextField();
        tid = new javax.swing.JTextField();
        tad = new javax.swing.JTextField();
        tpn = new javax.swing.JTextField();
        tsal = new javax.swing.JTextField();
        tidp = new javax.swing.JComboBox<>();
        td = new javax.swing.JComboBox<>();
        tm = new javax.swing.JComboBox<>();
        ty = new javax.swing.JComboBox<>();
        tgen = new javax.swing.JComboBox<>();
        t9 = new javax.swing.JButton();
        t10 = new javax.swing.JButton();
        ta1 = new javax.swing.JLabel();
        ta2 = new javax.swing.JLabel();
        ta3 = new javax.swing.JLabel();
        ta4 = new javax.swing.JLabel();
        ta5 = new javax.swing.JLabel();
        ta6 = new javax.swing.JLabel();
        ta7 = new javax.swing.JLabel();
        ta8 = new javax.swing.JLabel();
        ta10 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tqu = new javax.swing.JTextField();
        ta9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("MODIFY  EMPLOYEE");

        jLabel4.setText("EMPLOYEE NAME");

        jLabel5.setText("ID NO.");

        jLabel6.setText("ADDRESS");

        jLabel7.setText("PHONE NUMBER");

        jLabel8.setText("ID PROOF");

        jLabel9.setText("SALARY");

        jLabel10.setText("DATE OF BIRTH");

        jLabel11.setText("GENDER");

        tpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpnActionPerformed(evt);
            }
        });

        tsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsalActionPerformed(evt);
            }
        });

        tidp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Aadhar card", "Pan card", "Voter card", "Passport" }));

        td.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DATE", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        tm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MONTH", "jan ", "feb", "mar", "apr", "may", "jun", "july", "aug", "sep", "oct", "nov", "dec", " " }));

        ty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YEAR", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));

        tgen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Transgender" }));

        t9.setText("MODIFY");
        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });

        t10.setText("EXIT");
        t10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t10ActionPerformed(evt);
            }
        });

        ta1.setText("Fill employee name");

        ta2.setText("Fill Id no.");

        ta3.setText("Fill address");

        ta4.setText("Fill phone no.");

        ta5.setText("Fill Id proof");

        ta6.setText("Fill date of birth");

        ta7.setText("Fill gender");

        ta8.setText("Fill salary");

        ta10.setText("SEARCH");
        ta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ta10ActionPerformed(evt);
            }
        });

        jLabel12.setText("QUALIFICATION");

        ta9.setText("Fill qualification");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel11))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(td, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(t9)
                                            .addGap(63, 63, 63)
                                            .addComponent(t10))
                                        .addComponent(tidp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tem, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tad, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tpn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tgen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tsal, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tqu, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ta8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ta1)
                                        .addComponent(ta2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ta3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ta4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ta5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ta6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ta7, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ta10))
                                    .addComponent(ta9)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel3)))
                .addContainerGap(718, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ta10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ta1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(ta2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ta3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ta4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(tpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tidp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ta5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(td, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ta6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ta7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ta8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(tsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(ta9))
                    .addComponent(tqu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t9)
                    .addComponent(t10))
                .addContainerGap(371, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ta10ActionPerformed
  int t=0;
             if(tid.getText().length()==0)
                 ta2.setVisible(true);
             else
             {
      try {
          ta2.setVisible(false);
          t=1; int id = Integer.parseInt(tid.getText());
          String QueryString = "Select * from employee where tid="+id;
          Statement statement = conn.createStatement();
          ResultSet rs = statement.executeQuery(QueryString);
          if (rs.next())
          {
              tem.setText(rs.getString("tem"));
              tad.setText(rs.getString("tad"));
              tpn.setText(rs.getString("tpn"));
              tidp.setSelectedItem(rs.getString("tidp"));
              td.setSelectedItem(rs.getString("td"));
              tm.setSelectedItem(rs.getString("tm"));
              ty.setSelectedItem(rs.getString("ty"));
              tgen.setSelectedItem(rs.getString("tgen"));
              tsal.setText(rs.getString("tsal"));
              tqu.setText(rs.getString("tqu"));
          }
          else
          {JOptionPane.showMessageDialog(null,"Please fill proper ID no");
          tid.requestFocus();
          tid.setText("");
             
          }
      } catch (SQLException ex) {
          Logger.getLogger(modifyemployee.class.getName()).log(Level.SEVERE, null, ex);
      }
                  
            

    }//GEN-LAST:event_ta10ActionPerformed
    }
    private void tpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpnActionPerformed

    private void tsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsalActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
       try {
           int t=0;
           if(tem.getText().length()==0)
               ta1.setVisible(true);
           else
           {
               ta1.setVisible(false);
               t=1;
           }
           if(tid.getText().length()==0)
               ta2.setVisible(true);
           else
           {
               ta2.setVisible(false);
               t=1;
           }
           if(tad.getText().length()==0)
               ta3.setVisible(true);
           else
           {
               ta3.setVisible(false);
               t=1;
           }
           if(tpn.getText().length()==0)
               ta4.setVisible(true);
           else
           {
               ta4.setVisible(false);
               t=1;
           }
           if(tidp.getSelectedIndex()==0)
               ta5.setVisible(true);
           else
           {
               ta5.setVisible(false);
               t=1;
           }
           if(tgen.getSelectedIndex()==0)
               ta7.setVisible(true);
           else
           {
               ta7.setVisible(false);
               t=1;
           }
           if(tsal.getText().length()==0)
               ta8.setVisible(true);
           else
           {
               ta8.setVisible(false);
               t=1;
           }
           if(tqu.getText().length()==0)
               ta9.setVisible(true);
           else
           {
               ta9.setVisible(false);
               t=1;
           }
           int id=Integer.parseInt(tid.getText());
           
           String em=tem.getText();
           String ad=tad.getText();
           String pn=tpn.getText();
           String idp=String.valueOf(tidp.getSelectedItem());
           String d=String.valueOf(td.getSelectedItem());
           String m=String.valueOf(tm.getSelectedItem());
           String y=String.valueOf(ty.getSelectedItem());
           String gen=String.valueOf(tgen.getSelectedItem());
           String sal=tsal.getText();
           String qu=tqu.getText();
           PreparedStatement stmt=conn.prepareStatement("insert into employee values(?,?,?,?,?,?,?,?,?,?,?)");
           stmt.setString(1,em);
           stmt.setInt(2,id);
           stmt.setString(3,ad);
           stmt.setString(4,pn);
           stmt.setString(5,idp);
           stmt.setString(6,d);
           stmt.setString(7,m);
           stmt.setString(8,y);
           stmt.setString(9,gen);
           stmt.setString(10,sal);
           stmt.setString(11,qu);
           
           
           stmt.executeUpdate();
           tem.setText("");
           tid.setText("");
           tad.setText("");
           tpn.setText("");
           tidp.setSelectedIndex(0);
           td.setSelectedIndex(0);
           tm.setSelectedIndex(0);
           ty.setSelectedIndex(0);
           tsal.setText("");
           tqu.setText("");
           tid.requestFocus();
           JOptionPane.showMessageDialog(null, "Record Saved");
       } catch (SQLException ex) {
           Logger.getLogger(modifyemployee.class.getName()).log(Level.SEVERE, null, ex);
       }
                 
           
    }//GEN-LAST:event_t9ActionPerformed
    
    private void t10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t10ActionPerformed
this.hide();        // TODO add your handling code here:
    }//GEN-LAST:event_t10ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifyemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new modifyemployee().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton t10;
    private javax.swing.JButton t9;
    private javax.swing.JLabel ta1;
    private javax.swing.JButton ta10;
    private javax.swing.JLabel ta2;
    private javax.swing.JLabel ta3;
    private javax.swing.JLabel ta4;
    private javax.swing.JLabel ta5;
    private javax.swing.JLabel ta6;
    private javax.swing.JLabel ta7;
    private javax.swing.JLabel ta8;
    private javax.swing.JLabel ta9;
    private javax.swing.JTextField tad;
    private javax.swing.JComboBox<String> td;
    private javax.swing.JTextField tem;
    private javax.swing.JComboBox<String> tgen;
    private javax.swing.JTextField tid;
    private javax.swing.JComboBox<String> tidp;
    private javax.swing.JComboBox<String> tm;
    private javax.swing.JTextField tpn;
    private javax.swing.JTextField tqu;
    private javax.swing.JTextField tsal;
    private javax.swing.JComboBox<String> ty;
    // End of variables declaration//GEN-END:variables

}
