
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class TALVEEN6 extends javax.swing.JFrame {

    /**
     * Creates new form TALVEEN6
     */
        Connection conn = null;
    final void getconnection()
    {
   
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
            } catch (InstantiationException | IllegalAccessException ex) {
                Logger.getLogger(TALVEEN5.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/customer","root","");
            } catch (SQLException ex) {
                Logger.getLogger(TALVEEN5.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TALVEEN5.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }


    public TALVEEN6() {
        initComponents();
        getconnection();
        ma1.setVisible(false);
        ma2.setVisible(false);
        ma3.setVisible(false);
        ma4.setVisible(false);
        ma5.setVisible(false);
        ma6.setVisible(false);
        ma7.setVisible(false);
        ma8.setVisible(false);
        ma9.setVisible(false);
        ma10.setVisible(false);
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mid = new javax.swing.JTextField();
        mcn = new javax.swing.JTextField();
        mpn = new javax.swing.JTextField();
        madd = new javax.swing.JTextField();
        ma1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        midp = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        mrn = new javax.swing.JTextField();
        mrt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        md = new javax.swing.JComboBox<>();
        mm = new javax.swing.JComboBox<>();
        my = new javax.swing.JComboBox<>();
        mda = new javax.swing.JComboBox<>();
        mmo = new javax.swing.JComboBox<>();
        mye = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        mta = new javax.swing.JTextField();
        m15 = new javax.swing.JButton();
        m16 = new javax.swing.JButton();
        ma2 = new javax.swing.JLabel();
        ma3 = new javax.swing.JLabel();
        ma4 = new javax.swing.JLabel();
        ma5 = new javax.swing.JLabel();
        ma6 = new javax.swing.JLabel();
        ma7 = new javax.swing.JLabel();
        ma8 = new javax.swing.JLabel();
        ma9 = new javax.swing.JLabel();
        ma10 = new javax.swing.JLabel();
        ma12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("MODIFY CUSTOMER DATA");

        jLabel2.setText(" Id no..");

        jLabel3.setText(" Customer name");

        jLabel4.setText("Phone no..");

        jLabel5.setText("Address");

        mcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcnActionPerformed(evt);
            }
        });

        mpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpnActionPerformed(evt);
            }
        });

        madd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maddActionPerformed(evt);
            }
        });

        ma1.setText(" Fill Id no.");

        jLabel13.setText("jLabel13");

        jLabel14.setText("jLabel14");

        jLabel15.setText("Id Proof");

        midp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Aadhar card", "Voter card", "Pan card" }));
        midp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midpActionPerformed(evt);
            }
        });

        jLabel16.setText(" Room no.");

        jLabel17.setText(" Room Type");

        mrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrtActionPerformed(evt);
            }
        });

        jLabel18.setText(" Date of arrival");

        jLabel19.setText(" Date of departure");

        md.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "jan", "feb", "mar", "apr", "may", "jun", "july", "aug", "sep", "oct", "nov", "dec" }));

        my.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        mda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "jan", "feb", "mar", "apr", "may", "jun", "july", "aug", "sep", "oct", "nov", "dec" }));

        mye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", " ", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        jLabel20.setText("Total amount");

        mta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtaActionPerformed(evt);
            }
        });

        m15.setText(" MODIFY");
        m15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m15ActionPerformed(evt);
            }
        });

        m16.setText("EXIT");
        m16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m16ActionPerformed(evt);
            }
        });

        ma2.setText(" Fill customer name");

        ma3.setText(" Fill phone no.");

        ma4.setText(" Fill Address");

        ma5.setText("Fill Id proof");

        ma6.setText("Fill room no.");

        ma7.setText(" Fill room type");

        ma8.setText("Fill date of arive");

        ma9.setText(" Fill date of departure");

        ma10.setText("Fill total amount");

        ma12.setText("SEARCH");
        ma12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ma12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(1368, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mcn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mpn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(madd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(midp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel13)
                                                    .addGap(37, 37, 37))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ma2)
                                                    .addComponent(ma1))
                                                .addComponent(ma3)
                                                .addComponent(ma4)
                                                .addComponent(ma5)
                                                .addComponent(ma6)
                                                .addComponent(ma7)
                                                .addComponent(ma8))
                                            .addComponent(ma9)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(ma10)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(md, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(my, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(mda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(m15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                        .addComponent(m16)
                                        .addGap(25, 25, 25))
                                    .addComponent(mrt)
                                    .addComponent(mrn)
                                    .addComponent(mta))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(541, 541, 541)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 630, Short.MAX_VALUE)
                .addComponent(ma12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(ma12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ma1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ma2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ma3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(madd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(ma4)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(midp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ma5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(ma6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ma7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(md, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(my, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ma8))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ma9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ma10))))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m15)
                            .addComponent(m16))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addComponent(jLabel14))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcnActionPerformed

    private void mpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpnActionPerformed

    private void maddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maddActionPerformed

    private void midpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midpActionPerformed

    private void mrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrtActionPerformed

    private void mtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mtaActionPerformed

    private void m15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m15ActionPerformed

        {
                try {
                    int t=0;
                    if(mid.getText().length()==0)
                        ma1.setVisible(true);
                    else
                    {
                        ma1.setVisible(false);
                        t=1;
                    }
                    if(mcn.getText().length()==0)
                        ma2.setVisible(true);
                    else
                    {
                        ma2.setVisible(false);
                        t=1;
                    }
                    if(mpn.getText().length()==0)
                        ma3.setVisible(true);
                    else
                    {
                        ma3.setVisible(false);
                        t=1;
                    }
                    if(madd.getText().length()==0)
                        ma4.setVisible(true);
                    else
                    {
                        ma4.setVisible(false);
                        t=1;
                    }
                    if(midp.getSelectedIndex()==0)
                        ma5.setVisible(true);
                    else
                    {
                        ma5.setVisible(false);
                        t=1;
                    }
                    if(mrn.getText().length()==0)
                        ma6.setVisible(true);
                    else
                    {
                        ma6.setVisible(false);
                        t=1;
                    }
                    if(mrt.getText().length()==0)
                        ma7.setVisible(true);
                    else
                    {
                        ma7.setVisible(false);
                        t=1;
                    }
                    if(mta.getText().length()==0)
                        ma10.setVisible(true);
                    else
                    {
                        ma10.setVisible(false);
                        t=1;
                    }
                    int id=Integer.parseInt(mid.getText());
                    
                    String cn=mcn.getText();
                    String pn=mpn.getText();
                    String add=madd.getText();
                    String idp=String.valueOf(midp.getSelectedItem());
                    String rn=mrn.getText();
                    String rt=mrt.getText();
                    String d=String.valueOf(md.getSelectedItem());
                    String m=String.valueOf(mm.getSelectedItem());
                    String y=String.valueOf(my.getSelectedItem());
                    String da=String.valueOf(mda.getSelectedItem());
                    String mo=String.valueOf(mmo.getSelectedItem());
                    String ye=String.valueOf(mye.getSelectedItem());
                    String ta=mta.getText();
                    PreparedStatement stmt=conn.prepareStatement("insert into customer values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                    stmt.setInt(1,id);
                    stmt.setString(2,cn);
                    stmt.setString(3,pn);
                    stmt.setString(4,add);
                    stmt.setString(5,idp);
                    stmt.setString(6,rn);
                    stmt.setString(7,rt);
                    stmt.setString(8,d);
                    stmt.setString(9,m);
                    stmt.setString(10,y);
                    stmt.setString(11,da);
                    stmt.setString(12,mo);
                    stmt.setString(13,ye);
                    stmt.setString(14,ta);
                    
                    
                    stmt.executeUpdate();
                    mid.setText("");
                    mcn.setText("");
                    mpn.setText("");
                    madd.setText("");
                    midp.setSelectedIndex(0);
                    mrn.setText("");
                    mrt.setText("");
                    md.setSelectedIndex(0);
                    mm.setSelectedIndex(0);
                    my.setSelectedIndex(0);
                    mda.setSelectedIndex(0);
                    mmo.setSelectedIndex(0);
                    mye.setSelectedIndex(0);
                    mta.setText("");
                    mid.requestFocus();
                    JOptionPane.showMessageDialog(null, "Record Saved");
                    // TODO add your handling code here:
                } catch (SQLException ex) {
                    Logger.getLogger(TALVEEN6.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_m15ActionPerformed
    }
    private void ma12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ma12ActionPerformed
             int t=0;
             if(mid.getText().length()==0)
                 ma1.setVisible(true);
             else
             {
                 try {
                     ma1.setVisible(false);
                     t=1; 
                     int id = Integer.parseInt(mid.getText());
                     String QueryString = "Select * from customer where mid="+id;
                     Statement statement = conn.createStatement();
                     ResultSet rs = statement.executeQuery(QueryString);
                     if (rs.next())
                     {
                         mcn.setText(rs.getString("mcn"));
                         mpn.setText(rs.getString("mpn"));
                         madd.setText(rs.getString("madd"));
                         midp.setSelectedItem(rs.getString("midp"));
                         mrn.setText(rs.getString("mrn"));
                         mrt.setText(rs.getString("mrt"));
                         md.setSelectedItem(rs.getString("md"));
                         mm.setSelectedItem(rs.getString("mm"));
                         my.setSelectedItem(rs.getString("my"));
                         mda.setSelectedItem(rs.getString("mda"));
                         mmo.setSelectedItem(rs.getString("mmo"));
                         mye.setSelectedItem(rs.getString("mye"));
                         mta.setText(rs.getString("mta"));
                     }
                     else
                     {JOptionPane.showMessageDialog(null,"Please fill proper ID no");
                     mid.requestFocus();
                     mid.setText("");
                     
                     }
                     // TODO add your handling code here:
                 } catch (SQLException ex) {
                     Logger.getLogger(TALVEEN6.class.getName()).log(Level.SEVERE, null, ex);
                 
    }//GEN-LAST:event_ma12ActionPerformed
             }}              
    private void m16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m16ActionPerformed
this.hide();        // TODO add your handling code here:
    }//GEN-LAST:event_m16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TALVEEN6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TALVEEN6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TALVEEN6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TALVEEN6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TALVEEN6().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton m15;
    private javax.swing.JButton m16;
    private javax.swing.JLabel ma1;
    private javax.swing.JLabel ma10;
    private javax.swing.JButton ma12;
    private javax.swing.JLabel ma2;
    private javax.swing.JLabel ma3;
    private javax.swing.JLabel ma4;
    private javax.swing.JLabel ma5;
    private javax.swing.JLabel ma6;
    private javax.swing.JLabel ma7;
    private javax.swing.JLabel ma8;
    private javax.swing.JLabel ma9;
    private javax.swing.JTextField madd;
    private javax.swing.JTextField mcn;
    private javax.swing.JComboBox<String> md;
    private javax.swing.JComboBox<String> mda;
    private javax.swing.JTextField mid;
    private javax.swing.JComboBox<String> midp;
    private javax.swing.JComboBox<String> mm;
    private javax.swing.JComboBox<String> mmo;
    private javax.swing.JTextField mpn;
    private javax.swing.JTextField mrn;
    private javax.swing.JTextField mrt;
    private javax.swing.JTextField mta;
    private javax.swing.JComboBox<String> my;
    private javax.swing.JComboBox<String> mye;
    // End of variables declaration//GEN-END:variables
}
